services:
  frontend:
    image: checkmate-frontend-express:${VERSION}
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    volumes:
      - ./cert/:/etc/checkmate/ssl/certs
    env_file: "auth.env"
    environment:
      - AUTH_ROOT=https://auth-service:9443
      - API_ROOT=https://database-service:8443
      - FRONTEND_PORT=${FRONTEND_PORT}
      - CERT_LOCATION=/etc/checkmate/ssl/certs/cert.p12
  auth-service:
    image: checkmate-auth-service:${VERSION}
    ports:
      - ${AUTH_PORT}:9443
    volumes:
      - checkmate-db:/usr/share/checkmate
      - ./cert/:/etc/checkmate/ssl/certs
    env_file: "auth.env"
    environment:
      - OZ_DATABASE_PATH=/usr/share/checkmate/tasks.db
      - FRONTEND_ROOT=https://${DOMAIN}:${FRONTEND_PORT}
      - CERT_LOCATION=/etc/checkmate/ssl/certs/cert.p12
  database-service:
    image: checkmate-database-service:${VERSION}
    ports:
      - ${API_PORT}:8443
    volumes:
      - checkmate-db:/usr/share/checkmate
      - ./cert/:/etc/checkmate/ssl/certs
    env_file: "auth.env"
    environment:
      - OZ_DATABASE_PATH=/usr/share/checkmate/tasks.db
      - CERT_LOCATION=/etc/checkmate/ssl/certs/cert.p12

volumes:
  checkmate-db: